# Generated by Django 3.1.1 on 2020-09-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='state',
            field=models.CharField(default='https://voterservices.elections.maryland.gov/OnlineVoterRegistration/InstructionsStep1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zip',
            name='link',
            field=models.URLField(default='https://voterservices.elections.maryland.gov/OnlineVoterRegistration/InstructionsStep1'),
            preserve_default=False,
        ),
    ]
