# Generated by Django 3.1.1 on 2020-09-17 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200917_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(help_text='Format: 1234567890', max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be 10 digits and entered in the format: '1234567890'.", regex='^\\d{10}$')]),
        ),
    ]
