# Generated by Django 3.1.1 on 2020-09-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200917_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zip',
            name='mail_only',
            field=models.CharField(max_length=100),
        ),
    ]
